# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from config import manager
from connector import c,db
from datetime import datetime
from PyQt6.QtWidgets import QMessageBox

class Ui_ClientCreate(object):
    def setupUi(self, ClientCreateWindow):
        ClientCreateWindow.setObjectName("ClientCreateWindow")
        ClientCreateWindow.resize(598, 478)
        self.centralwidget = QtWidgets.QWidget(parent=ClientCreateWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ClientCreateWindow = ClientCreateWindow
        self.ClientCreateWindow.closeEvent = self.close_event
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 231, 20))
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 571, 361))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 81, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 41, 20))
        self.label_3.setObjectName("label_3")
        self.lineEdit_surname = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_surname.setGeometry(QtCore.QRect(90, 10, 471, 21))
        self.lineEdit_surname.setObjectName("lineEdit")
        self.lineEdit_name = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_name.setGeometry(QtCore.QRect(50, 40, 171, 21))
        self.lineEdit_name.setObjectName("lineEdit_2")
        self.lineEdit_patronymic = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_patronymic.setGeometry(QtCore.QRect(380, 40, 181, 21))
        self.lineEdit_patronymic.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(300, 40, 71, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 80, 121, 20))
        self.label_5.setObjectName("label_5")
        self.dateEdit_birthday = QtWidgets.QDateEdit(parent=self.groupBox)
        self.dateEdit_birthday.setGeometry(QtCore.QRect(130, 80, 110, 26))
        self.dateEdit_birthday.setObjectName("dateEdit")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(250, 80, 151, 20))
        self.label_6.setObjectName("label_6")
        self.lineEdit_phone = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_phone.setGeometry(QtCore.QRect(410, 80, 151, 26))
        self.lineEdit_phone.setObjectName("lineEdit_4")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 140, 141, 20))
        self.label_7.setObjectName("label_7")
        self.lineEdit_serial = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_serial.setGeometry(QtCore.QRect(60, 180, 61, 21))
        self.lineEdit_serial.setObjectName("lineEdit_5")
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 180, 51, 20))
        self.label_8.setObjectName("label_8")
        self.lineEdit_number = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_number.setGeometry(QtCore.QRect(190, 180, 91, 21))
        self.lineEdit_number.setText("")
        self.lineEdit_number.setObjectName("lineEdit_6")
        self.label_9 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(130, 180, 61, 20))
        self.label_9.setObjectName("label_9")
        self.dateEdit_givenBy = QtWidgets.QDateEdit(parent=self.groupBox)
        self.dateEdit_givenBy.setGeometry(QtCore.QRect(450, 180, 110, 26))
        self.dateEdit_givenBy.setObjectName("dateEdit_2")
        self.label_10 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(350, 180, 121, 20))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 220, 181, 20))
        self.label_11.setObjectName("label_11")
        self.textEdit_givenby = QtWidgets.QTextEdit(parent=self.groupBox)
        self.textEdit_givenby.setGeometry(QtCore.QRect(10, 250, 551, 101))
        self.textEdit_givenby.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(490, 420, 101, 29))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.addClient)
        ClientCreateWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=ClientCreateWindow)
        self.statusbar.setObjectName("statusbar")
        ClientCreateWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ClientCreateWindow)
        QtCore.QMetaObject.connectSlotsByName(ClientCreateWindow)

    def retranslateUi(self, ClientCreateWindow):
        _translate = QtCore.QCoreApplication.translate
        ClientCreateWindow.setWindowTitle(_translate("ClientCreateWindow", "Добавление клиента"))
        self.label.setText(_translate("ClientCreateWindow", "Добавление сведений о клиенте"))
        self.label_2.setText(_translate("ClientCreateWindow", "Фамилия:"))
        self.label_3.setText(_translate("ClientCreateWindow", "Имя:"))
        self.label_4.setText(_translate("ClientCreateWindow", "Отчество:"))
        self.label_5.setText(_translate("ClientCreateWindow", "Дата рождения:"))
        self.label_6.setText(_translate("ClientCreateWindow", "Контактный телефон:"))
        self.label_7.setText(_translate("ClientCreateWindow", "Паспотные данные"))
        self.label_8.setText(_translate("ClientCreateWindow", "Серия:"))
        self.label_9.setText(_translate("ClientCreateWindow", "Номер:"))
        self.label_10.setText(_translate("ClientCreateWindow", "Дата выдачи:"))
        self.label_11.setText(_translate("ClientCreateWindow", "Орган выдачи паспорта:"))
        self.pushButton.setText(_translate("ClientCreateWindow", "Применить"))
        self.lineEdit_phone.setInputMask("(999) 999-99-99")
        self.lineEdit_serial.setValidator(QtGui.QIntValidator())
        self.lineEdit_number.setValidator(QtGui.QIntValidator())
        self.lineEdit_number.setMaxLength(6)
        self.lineEdit_serial.setMaxLength(4)

    def addClient(self):
        if self.lineEdit_serial.text().strip() == "" or self.lineEdit_name.text().strip() == "" or self.lineEdit_number.text().strip() == "" or self.lineEdit_patronymic.text().strip() == "" or self.lineEdit_phone.text().strip() == "" or self.lineEdit_surname.text().strip() == "" or self.textEdit_givenby.toPlainText().strip() == "":
            QMessageBox.critical(None,"Ошибка","Некорректно заполнены данные",QMessageBox.StandardButton.Ok)
        else:
            birthday = self.dateEdit_birthday.date().toString("yyyy-MM-dd")
            c.execute("INSERT INTO users(Surname,Name,Patronymic,DateOfBirth,Phone,RoleID) VALUE(%s,%s,%s,%s,%s,%s)",(self.lineEdit_surname.text(),self.lineEdit_name.text(),self.lineEdit_patronymic.text(),birthday,self.lineEdit_phone.text(),3,))
            db.commit()
            c.execute("SELECT LAST_INSERT_ID()")
            userID = c.fetchone()[0]
            dateGiven = self.dateEdit_givenBy.date().toString("yyyy-MM-dd")
            c.execute("INSERT INTO clients(UserID,Serial,Number,DateGivenBy,GivenBy) VALUES (%s,%s,%s,%s,%s)",(userID,self.lineEdit_serial.text(),self.lineEdit_number.text(),dateGiven,self.textEdit_givenby.toPlainText(),))
            db.commit()
            QMessageBox.information(None,"Успешно!","Новый клиент добавлен в БД",QMessageBox.StandardButton.Ok)
            self.ClientCreateWindow.close()
            
    def close_event(self, event):
        manager.show_orderCreateWindow()
        event.accept()
