# Form implementation generated from reading ui file 'orderCreate.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from config import manager

class Ui_OrderCreate(object):
    def setupUi(self, OrderCreateWindow):
        OrderCreateWindow.setObjectName("OrderCreateWindow")
        OrderCreateWindow.resize(1399, 674)
        self.centralwidget = QtWidgets.QWidget(parent=OrderCreateWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.OrderCreateWindow = OrderCreateWindow
        self.OrderCreateWindow.closeEvent = self.close_event
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 211, 29))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 50, 71, 20))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(80, 50, 601, 26))
        self.comboBox.setObjectName("comboBox")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(450, 80, 231, 29))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.openClientCreate)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 121, 20))
        self.label_2.setObjectName("label_2")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 160, 671, 421))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget_2 = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(710, 160, 671, 461))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(6)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(710, 130, 161, 20))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(880, 130, 501, 26))
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 610, 63, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(240, 610, 63, 20))
        self.label_5.setObjectName("label_5")
        OrderCreateWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=OrderCreateWindow)
        self.statusbar.setObjectName("statusbar")
        OrderCreateWindow.setStatusBar(self.statusbar)

        self.retranslateUi(OrderCreateWindow)
        QtCore.QMetaObject.connectSlotsByName(OrderCreateWindow)

    def retranslateUi(self, OrderCreateWindow):
        _translate = QtCore.QCoreApplication.translate
        OrderCreateWindow.setWindowTitle(_translate("OrderCreateWindow", "Создание нового заказа"))
        self.pushButton.setText(_translate("OrderCreateWindow", "Добавить заказ в систему"))
        self.label.setText(_translate("OrderCreateWindow", "Клиент:"))
        self.pushButton_2.setText(_translate("OrderCreateWindow", "Добавить нового клиента"))
        self.label_2.setText(_translate("OrderCreateWindow", "Корзина заказа:"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("OrderCreateWindow", "Артикул"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("OrderCreateWindow", "Наименование"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("OrderCreateWindow", "Цена"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("OrderCreateWindow", "Кол-во"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("OrderCreateWindow", "Стоимость"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("OrderCreateWindow", " "))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("OrderCreateWindow", "Артикул"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("OrderCreateWindow", "Наименование"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("OrderCreateWindow", "Цена"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("OrderCreateWindow", "Кол-во"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("OrderCreateWindow", "Стоимость"))
        self.label_3.setText(_translate("OrderCreateWindow", "Поиск наименований:"))
        self.label_4.setText(_translate("OrderCreateWindow", "TextLabel"))
        self.label_5.setText(_translate("OrderCreateWindow", "TextLabel"))

    def openClientCreate(self):
        manager.show_clientCreateWindow()

    def close_event(self, event):
        if manager.current_window == manager.clientCreate_window:
            pass
        else:
            manager.show_operateWindow()
            event.accept()

