# Form implementation generated from reading ui file 'orderCreate.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from config import manager
from connector import c,db

class Ui_OrderCreate(object):
    def __init__(self):
        self.currentTovarIndexes = []
    def setupUi(self, OrderCreateWindow):
        OrderCreateWindow.setObjectName("OrderCreateWindow")
        OrderCreateWindow.setGeometry(50,100,1399, 674)
        
        self.centralwidget = QtWidgets.QWidget(parent=OrderCreateWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.OrderCreateWindow = OrderCreateWindow
        self.OrderCreateWindow.closeEvent = self.close_event
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 211, 29))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 50, 71, 20))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(80, 50, 601, 26))
        self.comboBox.setObjectName("comboBox")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(450, 80, 231, 29))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.openClientCreate)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 121, 20))
        self.label_2.setObjectName("label_2")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 160, 671, 421))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget_2 = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(710, 160, 671, 461))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(6)
        self.tableWidget_2.setRowCount(0)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.tableWidget_2.setEditTriggers(QtWidgets.QTableWidget.EditTrigger.NoEditTriggers)
        self.tableWidget_2.setSelectionMode(QtWidgets.QTableWidget.SelectionMode.SingleSelection)
        self.tableWidget_2.setSelectionBehavior(QtWidgets.QTableWidget.SelectionBehavior.SelectRows)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(710, 130, 161, 20))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(880, 130, 501, 26))
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 610, 63, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(240, 610, 63, 20))
        self.label_5.setObjectName("label_5")
        OrderCreateWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=OrderCreateWindow)
        self.statusbar.setObjectName("statusbar")
        OrderCreateWindow.setStatusBar(self.statusbar)

        self.retranslateUi(OrderCreateWindow)
        QtCore.QMetaObject.connectSlotsByName(OrderCreateWindow)

    def retranslateUi(self, OrderCreateWindow):
        _translate = QtCore.QCoreApplication.translate
        OrderCreateWindow.setWindowTitle(_translate("OrderCreateWindow", "Создание нового заказа"))
        self.pushButton.setText(_translate("OrderCreateWindow", "Добавить заказ в систему"))
        self.label.setText(_translate("OrderCreateWindow", "Клиент:"))
        self.pushButton_2.setText(_translate("OrderCreateWindow", "Добавить нового клиента"))
        self.label_2.setText(_translate("OrderCreateWindow", "Корзина заказа:"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("OrderCreateWindow", "Артикул"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("OrderCreateWindow", "Наименование"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("OrderCreateWindow", "Цена"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("OrderCreateWindow", "Кол-во"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("OrderCreateWindow", "Стоимость"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("OrderCreateWindow", " "))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("OrderCreateWindow", "Артикул"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("OrderCreateWindow", "Наименование"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("OrderCreateWindow", "Гарантия"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("OrderCreateWindow", "Стоимость"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("OrderCreateWindow", "Остаток"))
        self.label_3.setText(_translate("OrderCreateWindow", "Поиск наименований:"))
        self.label_4.setText(_translate("OrderCreateWindow", "TextLabel"))
        self.label_5.setText(_translate("OrderCreateWindow", "TextLabel"))
        self.rightTableInit()
    def openClientCreate(self):
        manager.show_clientCreateWindow()

    def rightTableInit(self):
        if self.currentTovarIndexes:
            placeholders = ','.join(['%s'] * len(self.currentTovarIndexes))
            c.execute(f"SELECT * FROM tovar WHERE ID NOT IN ({placeholders})", self.currentTovarIndexes)
            result = c.fetchall()
        else:
            c.execute("SELECT * FROM tovar")
            result = c.fetchall()

        self.tableWidget_2.setRowCount(len(result))
        for i in range(len(result)):
            item = QtWidgets.QTableWidgetItem(str(result[i][0]))
            self.tableWidget_2.setItem(i,0,item)
            
            c.execute("SELECT Value FROM typetovar WHERE ID = %s",(result[i][3],))
            type_name = c.fetchone()[0]
            c.execute("SELECT Value FROM manufacturer WHERE ID = %s",(result[i][2],))
            manufacture_name = c.fetchone()[0]
            
            item = QtWidgets.QTableWidgetItem(f"{type_name} {manufacture_name} {result[i][1]}")
            self.tableWidget_2.setItem(i,1,item)
            
            c.execute("SELECT Value FROM garantytype WHERE ID = %s",(result[i][6],))
            garant_type = c.fetchone()[0]
            item = QtWidgets.QTableWidgetItem(f"{result[i][5]} {garant_type}")
            self.tableWidget_2.setItem(i,2,item)

            item = QtWidgets.QTableWidgetItem(str(result[i][4]))
            self.tableWidget_2.setItem(i,3,item)
            item = QtWidgets.QTableWidgetItem(str(result[i][7]))
            self.tableWidget_2.setItem(i,4,item)

            pushbutton = QtWidgets.QPushButton()
            pushbutton.setText("+")
            pushbutton.clicked.connect(lambda checked, row=i: self.tableButtonClicked(row))
            widget = QtWidgets.QWidget()
            layout = QtWidgets.QHBoxLayout(widget)
            layout.addWidget(pushbutton)
            layout.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
            layout.setContentsMargins(0, 0, 0, 0)
            self.tableWidget_2.setCellWidget(i, 5, widget)

        self.tableWidget_2.horizontalHeader().setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeMode.ResizeToContents)
        self.tableWidget_2.horizontalHeader().setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeMode.Stretch)
        self.tableWidget_2.horizontalHeader().setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeMode.ResizeToContents)
        self.tableWidget_2.horizontalHeader().setSectionResizeMode(4, QtWidgets.QHeaderView.ResizeMode.ResizeToContents)
        self.tableWidget_2.horizontalHeader().setSectionResizeMode(5, QtWidgets.QHeaderView.ResizeMode.ResizeToContents)

    def tableButtonClicked(self,row):
        row_data = self.tableWidget_2.item(row, 0).text()
        self.currentTovarIndexes.append(row_data)
        self.rightTableInit()
        self.leftTableInit()

    def tableButtonUnClicked(self,row):
        row_data = self.tableWidget.item(row, 0).text()
        self.currentTovarIndexes.remove(row_data)
        self.rightTableInit()
        self.leftTableInit()

    def leftTableInit(self):
        if self.currentTovarIndexes:
            placeholders = ','.join(['%s'] * len(self.currentTovarIndexes))
            c.execute(f"SELECT * FROM tovar WHERE ID IN ({placeholders})", self.currentTovarIndexes)
            result = c.fetchall()
        else:
            result = []

        # Сохраняем текущие значения spinbox'ов перед обновлением таблицы
        saved_values = {}
        for i in range(self.tableWidget.rowCount()):
            cwidget = self.tableWidget.cellWidget(i, 3)
            if cwidget is not None:
                cspinbox = cwidget.findChild(QtWidgets.QSpinBox)
                if cspinbox is not None:
                    item = self.tableWidget.item(i, 0)
                    if item is not None:
                        tovar_id = item.text()
                        saved_values[tovar_id] = cspinbox.value()

        self.tableWidget.setRowCount(len(result))
        for i in range(len(result)):
            item = QtWidgets.QTableWidgetItem(str(result[i][0]))
            self.tableWidget.setItem(i,0,item)
            
            c.execute("SELECT Value FROM typetovar WHERE ID = %s",(result[i][3],))
            type_name = c.fetchone()[0]
            c.execute("SELECT Value FROM manufacturer WHERE ID = %s",(result[i][2],))
            manufacture_name = c.fetchone()[0]
            
            item = QtWidgets.QTableWidgetItem(f"{type_name} {manufacture_name} {result[i][1]}")
            self.tableWidget.setItem(i,1,item)
            
            item = QtWidgets.QTableWidgetItem(str(result[i][4]))
            self.tableWidget.setItem(i,2,item)

            spinbox = QtWidgets.QSpinBox()
            spinbox.setMinimum(1)
            spinbox.setMaximum(result[i][7])
            
            # Восстанавливаем сохраненное значение или устанавливаем 1 по умолчанию
            tovar_id = str(result[i][0])
            if tovar_id in saved_values:
                spinbox.setValue(saved_values[tovar_id])
            else:
                spinbox.setValue(1)
                
            # Передаем номер строки в функцию
            spinbox.valueChanged.connect(lambda value, row=i: self.spinboxchange(row))
            widget1 = QtWidgets.QWidget()
            layout1 = QtWidgets.QHBoxLayout(widget1)
            layout1.addWidget(spinbox)
            layout1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
            layout1.setContentsMargins(0, 0, 0, 0)
            self.tableWidget.setCellWidget(i, 3, widget1)

            # Сразу обновляем стоимость для текущего значения
            costn = spinbox.value()
            item = QtWidgets.QTableWidgetItem(str(result[i][4] * costn))
            self.tableWidget.setItem(i,4,item)

            pushbutton = QtWidgets.QPushButton()
            pushbutton.setText("-")
            pushbutton.clicked.connect(lambda checked, row=i: self.tableButtonUnClicked(row))
            widget2 = QtWidgets.QWidget()
            layout2 = QtWidgets.QHBoxLayout(widget2)
            layout2.addWidget(pushbutton)
            layout2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
            layout2.setContentsMargins(0, 0, 0, 0)
            self.tableWidget.setCellWidget(i, 5, widget2)

        self.tableWidget.horizontalHeader().setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeMode.ResizeToContents)
        self.tableWidget.horizontalHeader().setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeMode.Stretch)
        self.tableWidget.horizontalHeader().setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeMode.ResizeToContents)
        self.tableWidget.horizontalHeader().setSectionResizeMode(4, QtWidgets.QHeaderView.ResizeMode.ResizeToContents)
        self.tableWidget.horizontalHeader().setSectionResizeMode(5, QtWidgets.QHeaderView.ResizeMode.ResizeToContents)

    def spinboxchange(self, row):
        """Обновляет стоимость для указанной строки"""
        cwidget = self.tableWidget.cellWidget(row, 3)
        if cwidget is not None:
            cspinbox = cwidget.findChild(QtWidgets.QSpinBox)
            if cspinbox is not None:
                price_item = self.tableWidget.item(row, 2)
                if price_item is not None:
                    try:
                        price = float(price_item.text())
                        quantity = cspinbox.value()
                        cost_item = QtWidgets.QTableWidgetItem(str(price * quantity))
                        self.tableWidget.setItem(row, 4, cost_item)
                    except ValueError:
                        pass

    def close_event(self, event):
        if manager.current_window == manager.clientCreate_window:
            pass
        else:
            manager.show_operateWindow()
            event.accept()

